all:
  hosts:
    R1:
      ansible_host: 10.122.105.1
    R2:
      ansible_host: 10.122.105.2
    R3:
      ansible_host: 10.122.105.3
  vars:
    ansible_connection: network_cli
    ansible_user: root
    ansible_ssh_pass: cisco
    ansible_network_os: ios



